"""
/sharecard — Generate a shareable Kundli compatibility card image.

FSM flow:
  /sharecard → ask partner name → ask partner DOB → generate card → send photo
"""
import logging
from datetime import date

from aiogram import Router
from aiogram.filters import Command
from aiogram.fsm.context import FSMContext
from aiogram.fsm.state import State, StatesGroup
from aiogram.types import BufferedInputFile, Message

from dateutil import parser as dateparser

from app.database import AsyncSessionFactory
from app.services import user as user_service
from app.services.astrology import get_kundli
from app.services.vedic import guna_milan
from app.services.card_service import generate_compatibility_card

logger = logging.getLogger(__name__)
router = Router()


class ShareCardState(StatesGroup):
    partner_name = State()
    partner_dob  = State()


# ── /sharecard entry point ─────────────────────────────────────────────────────

@router.message(Command("sharecard"))
async def cmd_sharecard(message: Message, state: FSMContext) -> None:
    async with AsyncSessionFactory() as session:
        u = await user_service.get_or_create(session, message.from_user.id)
    lang = u.language or "en"

    if not u.is_onboarded:
        no_profile = (
            "Please set up your profile first with /start."
            if lang == "en"
            else "पहले /start से अपनी प्रोफ़ाइल बनाएं।"
        )
        await message.answer(no_profile)
        return

    msg = (
        "💑 *Kundli Compatibility Card*\n\nEnter your partner's name:"
        if lang == "en"
        else "💑 *कुंडली संगतता कार्ड*\n\nसाथी का नाम बताएं:"
    )
    await message.answer(msg, parse_mode="Markdown")
    await state.set_state(ShareCardState.partner_name)


# ── Step 1 — collect partner name ─────────────────────────────────────────────

@router.message(ShareCardState.partner_name)
async def sc_partner_name(message: Message, state: FSMContext) -> None:
    await state.update_data(partner_name=message.text.strip())

    async with AsyncSessionFactory() as session:
        u = await user_service.get_or_create(session, message.from_user.id)
    lang = u.language or "en"

    msg = (
        "Partner's date of birth? (e.g. 15 Mar 1992)"
        if lang == "en"
        else "साथी की जन्म तिथि? (जैसे 15 Mar 1992)"
    )
    await message.answer(msg)
    await state.set_state(ShareCardState.partner_dob)


# ── Step 2 — collect partner DOB, generate card ────────────────────────────────

@router.message(ShareCardState.partner_dob)
async def sc_partner_dob(message: Message, state: FSMContext) -> None:
    async with AsyncSessionFactory() as session:
        u = await user_service.get_or_create(session, message.from_user.id)
    lang = u.language or "en"

    # Parse date — ask again on failure
    try:
        partner_dob: date = dateparser.parse(
            message.text.strip(), dayfirst=True, fuzzy=True
        ).date()
    except Exception:
        bad_date_msg = (
            "⚠️ Couldn't parse that date. Please try again (e.g. *15 Mar 1992*)."
            if lang == "en"
            else "⚠️ तारीख समझ नहीं आई। दोबारा बताएं (जैसे *15 Mar 1992*)।"
        )
        await message.answer(bad_date_msg, parse_mode="Markdown")
        return

    data = await state.get_data()
    partner_name: str = data["partner_name"]
    await state.clear()

    # Waiting message
    wait_msg = (
        "💑 Generating compatibility card..."
        if lang == "en"
        else "💑 कार्ड बन रहा है…"
    )
    await message.answer(wait_msg)

    try:
        # User's kundli (uses stored birth data)
        k1 = get_kundli(
            u.birth_date,
            u.birth_lat,
            u.birth_lon,
            u.birth_time,
            u.timezone or "UTC",
        )
        # Partner's kundli — DOB only, no city/time (lat=0, lon=0, UTC)
        k2 = get_kundli(
            partner_dob,
            0.0,
            0.0,
            None,
            "UTC",
        )

        result = guna_milan(
            k1["nakshatra"], k1["rashi"],
            k2["nakshatra"], k2["rashi"],
        )

        card_bytes = await generate_compatibility_card(
            name1=u.name or "You",
            name2=partner_name,
            nakshatra1=k1["nakshatra"],
            rashi1=k1["rashi"],
            nakshatra2=k2["nakshatra"],
            rashi2=k2["rashi"],
            score=result["score"],
            compatibility=result["compatibility"],
            details=result["details"],
        )

        caption = (
            f"💑 *Kundli Compatibility*\n"
            f"{u.name or 'You'} × {partner_name} — *{result['score']}/36* ({result['compatibility']})\n\n"
            f"_Generated by @Nakshatra\\_Astrobot_ ✨"
        )

        photo = BufferedInputFile(card_bytes, filename="compatibility.png")
        await message.answer_photo(photo, caption=caption, parse_mode="Markdown")

    except Exception:
        logger.exception("ShareCard generation error for user %s", message.from_user.id)
        err_msg = (
            "⚠️ Something went wrong generating the card. Please try again."
            if lang == "en"
            else "⚠️ कार्ड बनाने में समस्या हुई। दोबारा कोशिश करें।"
        )
        await message.answer(err_msg)
